#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Thu Jul 15 13:33:47 2010

import os
import wx
import MySQLdb

# begin wxGlade: extracode
# end wxGlade



class Ventana(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Ventana.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_1 = wx.Panel(self, -1)
        self.db = MySQLdb.connect('localhost', 'yanina', 'yanina', 'yanina', charset='UTF8')
        
        #Apellido:Ingreso
        self.apellido = wx.StaticText(self.panel_1, -1, "Apellido del Socio:")
        self.apellido_ingreso = wx.TextCtrl(self.panel_1, -1, "")
        
        #Boton: Buscar Socio
        self.boton_bsocio = wx.Button(self.panel_1, -1, "Buscar")
        self.Bind(wx.EVT_BUTTON, self.OnBuscarSocio, self.boton_bsocio)
        
        #Titulo: Ingreso
        self.titulo = wx.StaticText(self.panel_1, -1, "Titulo de la Pelicula:")
        self.titulo_ingreso = wx.TextCtrl(self.panel_1, -1, "")
        
        #Boton: Buscar Titulo
        self.boton_btitulo = wx.Button(self.panel_1, -1, "Buscar")
        self.Bind(wx.EVT_BUTTON, self.OnBuscarTitulo, self.boton_btitulo)
        
        #Fecha Retiro: Ingreso
        self.fecha_retiro = wx.StaticText(self.panel_1, -1, "Fecha de Retiro:")
        self.fecha_retiro_ingreso = wx.DatePickerCtrl(self.panel_1, -1)
        
        #Fecha Devolucion: Ingreso
        self.fecha_devolucion = wx.StaticText(self.panel_1, -1, "Fecha de devolucion:")
        self.fecha_devolucion_ingreso = wx.DatePickerCtrl(self.panel_1, -1)
        
        #Botones:
        self.boton_aceptar = wx.Button(self.panel_1, -1, "Aceptar")
        self.boton_cancelar = wx.Button(self.panel_1, -1, "Cancelar")
        self.Bind(wx.EVT_BUTTON, self.OnAceptarBoton, self.boton_aceptar)
        self.Bind(wx.EVT_BUTTON, self.OnCancelarBoton, self.boton_cancelar)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Ventana.__set_properties
        self.SetTitle("Alquiler de Peliculas")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Ventana.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.GridSizer(5, 2, 0, 0)
        grid_sizer_3 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_2 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_1.Add(self.apellido, 0, 0, 0)
        grid_sizer_2.Add(self.apellido_ingreso, 0, 0, 0)
        grid_sizer_2.Add(self.boton_bsocio, 0, 0, 0)
        grid_sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.titulo, 0, 0, 0)
        grid_sizer_3.Add(self.titulo_ingreso, 0, 0, 0)
        grid_sizer_3.Add(self.boton_btitulo, 0, 0, 0)
        grid_sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.fecha_retiro, 0, 0, 0)
        grid_sizer_1.Add(self.fecha_retiro_ingreso, 0, 0, 0)
        grid_sizer_1.Add(self.fecha_devolucion, 0, 0, 0)
        grid_sizer_1.Add(self.fecha_devolucion_ingreso, 0, 0, 0)
        grid_sizer_1.Add(self.boton_aceptar, 0, 0, 0)
        grid_sizer_1.Add(self.boton_cancelar, 0, 0, 0)
        self.panel_1.SetSizer(grid_sizer_1)
        sizer_1.Add(self.panel_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade
    
    def OnBuscarSocio (self,event):
        # wxGlade: Ventana.<event_handler>
        buscar_socio = self.apellido_ingreso.GetValue ()
        
        #buscar en db
        c = self.db.cursor()
        c.execute('''SELECT id_socios, apellido, nombre, dni FROM tabla_socios WHERE apellido = %s''', (buscar_socio))
        q = c.fetchall()
        c.close()
        
        # Mensaje: Devolver un mensaje con los datos ingresados
        wx.MessageBox (u'\nSocio: %s' %(buscar_socio), u'Datos en busqueda', wx.OK | wx.ICON_INFORMATION, None)
    
        # Generar una lista donde se guardan los elementos solicitados anteriormente
        lista = []
        for elemento in q:
            lista.append( str(elemento[0])  + ' - ' + elemento[1] + ' - ' + elemento[2]+ ' - ' + str(elemento[3]))
           
                
        # Ventana donde se muestran los datos pedidos.
        dlg = wx.SingleChoiceDialog(None, 'Socios que se corresponden a su busqueda', 'Elige una opcion', lista, wx.CHOICEDLG_STYLE)
        
        if dlg.ShowModal() == wx.ID_OK:
            busqueda = dlg.GetStringSelection()
            id_mod = busqueda.strip()
            id_mod = id_mod.split("-")
            id_mod = id_mod [0]
            id_mod = int(id_mod)
            dlg.Destroy()
            self.apellido_ingreso.SetValue ('%s'% (busqueda))
            self.id_mod = id_mod
        
    def OnBuscarTitulo (self,event):
        
        # wxGlade: Ventana.<event_handler>
        buscar_peli = self.titulo_ingreso.GetValue ()
        c = self.db.cursor()
        c.execute('''SELECT id_peliculas, titulo FROM tabla_peliculas WHERE alquilado = "No" AND titulo = %s''', (buscar_peli))
        q = c.fetchall()
        c.close()

        # Mensaje: Devolver un mensaje con los datos ingresados
        wx.MessageBox (u'\nTítulo: %s' %(buscar_peli), u'Datos en busqueda', wx.OK | wx.ICON_INFORMATION, None)
    
        # Generar una lista donde se guardan los elementos solicitados anteriormente
        lista_p = []
        for elemento in q:
            lista_p.append( str(elemento[0]) + ' - ' + elemento[1] )
        # Ventana donde se muestran los datos pedidos.
        dlg = wx.SingleChoiceDialog(None, 'Titulos que se corresponden a su busqueda', 'Elige una opcion', lista_p, wx.CHOICEDLG_STYLE)
        
        if dlg.ShowModal() == wx.ID_OK:
            busqueda_p = dlg.GetStringSelection()
            id_mod = busqueda_p.strip()
            id_mod = id_mod.split("-")
            id_mod = id_mod [0]
            id_mod = int(id_mod)
            self.id_mod = id_mod
            dlg.Destroy()
            self.titulo_ingreso.SetValue ('%s'% (busqueda_p))
        
    def OnAceptarBoton(self,event):
                
        # wxGlade: Ventana.<event_handler>
        #traer datos de la db de la peli especifica
        id_pelimod = self.id_mod
        c = self.db.cursor()
        c.execute('''SELECT * FROM tabla_peliculas WHERE id_peliculas = %s''', (id_pelimod))
        q = c.fetchone()
        c.close()

        #subir la peli elegida como alquilada a la tabla de Peliculas              
        c = self.db.cursor()
        c.execute('''UPDATE tabla_peliculas SET alquilado = "Si" WHERE id_Peliculas = %s''', (id_pelimod))
        c.close()
        #subir a tabla_socios el id_peliculas y "Si" al campo prestamo            
        id_mod = self.id_mod

        #obtener valores de fecha retiro
        fr = self.fecha_retiro_ingreso.GetValue()
        
        #asignar lugares y valores a fecha RETIRO
        retirar = ('%04d/%02d/%02d' % (fr.GetYear(), fr.GetMonth()+1, fr.GetDay()))
        
        #obtener valores de fecha reintegro       
        fr = self.fecha_retiro_ingreso.GetValue()
        
        #asignar lugares y valores a fecha reintegro
        reintegro = ('%04d/%02d/%02d' % (fr.GetYear(), fr.GetMonth()+1,fr.GetDay()))
        
        c = self.db.cursor()
        c.execute('''INSERT INTO tabla_alquileres (id_socios, id_peliculas, fecha_retiro) VALUES (%s, %s, %s)''' ,(id_mod, id_pelimod, retirar,))
        c.close()
        
        wx.MessageBox (u'Las modificaciones ya fueron realizadas correstamente', u'Atención', wx.CANCEL|wx.ICON_INFORMATION, None)
                     
    # Cancelar: se cierra la ventana        
    def OnCancelarBoton(self, event):
        self.Close()
# end of class Ventana

    
if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = Ventana(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
