#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Thu Jul  8 14:03:04 2010

import os
import wx
import MySQLdb

# begin wxGlade: extracode
# end wxGlade



class Ventana(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Ventana.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.db = MySQLdb.connect('localhost', 'yanina', 'yanina', 'yanina', charset='UTF8')
        #Apellido:Ingreso
        self.apellido = wx.StaticText(self, -1, "Apellido:")
        self.apellido_ingreso = wx.TextCtrl(self, -1, "")
        
        #Nombre:Ingreso
        self.nombre = wx.StaticText(self, -1, "Nombre:")
        self.nombre_ingreso = wx.TextCtrl(self, -1, "")
        
        #DNI:Ingreso
        self.dni = wx.StaticText(self, -1, "DNI:")
        self.dni_ingreso = wx.TextCtrl(self, -1, "")
        
        #Tel:Ingreso
        self.tel = wx.StaticText(self, -1, "Tel:")
        self.tel_ingreso = wx.TextCtrl(self, -1, "")
        
        #Calle:Ingreso
        self.calle = wx.StaticText(self, -1, "Calle:")
        self.calle_ingreso = wx.TextCtrl(self, -1, "")
        
        #Numero:Ingreso
        self.numero = wx.StaticText(self, -1, "Numero:")
        self.numero_ingreso = wx.TextCtrl(self, -1, "")
        
        #Piso:Ingreso
        self.piso = wx.StaticText(self, -1, "Piso:")
        self.piso_ingreso = wx.TextCtrl(self, -1, "")
        
        #Dep:Ingreso
        self.dep = wx.StaticText(self, -1, "Dep:")
        self.dep_ingreso = wx.TextCtrl(self, -1, "")
        
        #Cp:Ingreso
        self.cp = wx.StaticText(self, -1, "Cp:")
        self.cp_ingreso = wx.TextCtrl(self, -1, "")
        
        #Localidad:Ingreso
        self.localidad = wx.StaticText(self, -1, "Localidad:")
        self.localidad_ingreso = wx.TextCtrl(self, -1, "")
        
        #Correo:Ingreso
        self.correo = wx.StaticText(self, -1, "Correo:")
        self.correo_ingreso = wx.TextCtrl(self, -1, "")
        
        #Botones
        self.boton_aceptar = wx.Button(self, -1, "Aceptar")
        self.boton_cancelar  = wx.Button(self, -1, "Cancelar")
        self.Bind(wx.EVT_BUTTON, self.OnAceptarBoton, self.boton_aceptar)
        self.Bind(wx.EVT_BUTTON, self.OnCancelarBoton, self.boton_cancelar)
        
        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Ventana.__set_properties
        self.SetTitle("Socios")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Ventana.__do_layout
        grid_sizer_6 = wx.GridSizer(9, 2, 0, 0)
        grid_sizer_12 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_11 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_10 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_9 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_8 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_7 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_6.Add(self.apellido, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_6.Add(self.apellido_ingreso, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_6.Add(self.nombre, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_6.Add(self.nombre_ingreso, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_6.Add(self.dni, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_6.Add(self.dni_ingreso, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_6.Add(self.tel, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_6.Add(self.tel_ingreso, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_6.Add(self.calle, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_6.Add(self.calle_ingreso, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_7.Add(self.numero, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_7.Add(self.numero_ingreso, 0, 0, 0)
        grid_sizer_6.Add(grid_sizer_7, 1, wx.EXPAND, 0)
        grid_sizer_8.Add(self.piso, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_8.Add(self.piso_ingreso, 0, 0, 0)
        grid_sizer_6.Add(grid_sizer_8, 1, wx.EXPAND, 0)
        grid_sizer_9.Add(self.dep, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_9.Add(self.dep_ingreso, 0, 0, 0)
        grid_sizer_6.Add(grid_sizer_9, 1, wx.EXPAND, 0)
        grid_sizer_10.Add(self.cp, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_10.Add(self.cp_ingreso, 0, 0, 0)
        grid_sizer_6.Add(grid_sizer_10, 1, wx.EXPAND, 0)
        grid_sizer_11.Add(self.localidad, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_11.Add(self.localidad_ingreso, 0, 0, 0)
        grid_sizer_6.Add(grid_sizer_11, 1, wx.EXPAND, 0)
        grid_sizer_12.Add(self.correo, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_12.Add(self.correo_ingreso, 0, 0, 0)
        grid_sizer_6.Add(grid_sizer_12, 1, wx.EXPAND, 0)
        grid_sizer_6.Add(self.boton_aceptar, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_6.Add(self.boton_cancelar, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        self.SetSizer(grid_sizer_6)
        grid_sizer_6.Fit(self)
        self.Layout()
        # end wxGlade
        
    def OnAceptarBoton(self,event):
        
         
         apellido = self.apellido_ingreso.GetValue()
         nombre = self.nombre_ingreso.GetValue()
         dni = self.dni_ingreso.GetValue()
         dni = str (dni)
         tel = self.tel_ingreso.GetValue()
         tel = str (tel)
         calle = self.calle_ingreso.GetValue()
         numero = self.numero_ingreso.GetValue()
         numero = str (numero)
         piso = self.piso_ingreso.GetValue()
         piso = str (piso)
         dep = self.dep_ingreso.GetValue()
         dep = str (dep)
         cp = self.cp_ingreso.GetValue()
         cp = str (cp)
         localidad = self.localidad_ingreso.GetValue()
         correo = self.correo_ingreso.GetValue()
         correo = str (correo)
         
         pass
         
         c = self.db.cursor()
         c.execute('''INSERT INTO tabla_socios (Apellido, Nombre, Dni,
         Tel, Calle, Num, Piso, dep, Cp, localidad, correo) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)''' , (apellido, nombre, dni, tel, calle, numero, piso, dep, cp, localidad, correo))
         c.close()
         
         # Mensaje: Devolver un mensaje con los datos ingresados
         wx.MessageBox (u'\nApellido: %s \nNombre: %s \nDNI: %s \nTel: %s \nCalle: %s\nNum: %s \nPiso: %s \nDep: %s \nCp: %s \nLocalidad: %s \nCorreo: %s' %(apellido, nombre, dni, tel, calle, numero, piso, dep, cp, localidad, correo), u'Datos Ingresados', wx.OK | wx.ICON_INFORMATION, None)
          
        
         apellido = self.apellido_ingreso.SetValue('')
         nombre = self.nombre_ingreso.SetValue('')
         dni = self.dni_ingreso.SetValue('')
         dni = str (dni)
         tel = self.tel_ingreso.SetValue('')
         tel = str (tel)
         calle = self.calle_ingreso.SetValue('')
         numero = self.numero_ingreso.SetValue('')
         numero = str (numero)
         piso = self.piso_ingreso.SetValue('')
         piso = str (piso)
         dep = self.dep_ingreso.SetValue('')
         dep = str (dep)
         cp = self.cp_ingreso.SetValue('')
         cp = str (cp)
         localidad = self.localidad_ingreso.SetValue('')
         correo = self.correo_ingreso.SetValue('')
         correo = str (correo) 
                      
    # Cancelar: se cierra la ventana        
    def OnCancelarBoton(self, event):
        self.Close()
# end of class Ventana


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = Ventana(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
